Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -101,30 +101,30 @@ jobs:
         run: snyk monitor --all-projects
 
       # OWASP Dependency-Check
-      #- name: Install OWASP Dependency-Check CLI
-      #  run: |
-      #    wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
-      #    unzip dependency-check-12.1.0-release.zip -d $HOME/dependency-check
-      #    chmod +x $HOME/dependency-check/dependency-check/bin/dependency-check.sh
-      #    echo "$HOME/dependency-check/dependency-check/bin" >> $GITHUB_PATH
+      - name: Install OWASP Dependency-Check CLI
+        run: |
+          wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
+          unzip dependency-check-12.1.0-release.zip -d $HOME/dependency-check
+          chmod +x $HOME/dependency-check/dependency-check/bin/dependency-check.sh
+          echo "$HOME/dependency-check/dependency-check/bin" >> $GITHUB_PATH
       
-      #- name: Run OWASP Dependency-Check Scan
-      #  run: |
-      #    mkdir -p dependency-check-report
-      #    $HOME/dependency-check/dependency-check/bin/dependency-check.sh \
-      #      --project "java-springboot-app" \
-      #      --scan . \
-      #      --format HTML \
-      #      --out dependency-check-report \
-      #      --nvdApiKey ${{ secrets.NVD_API_KEY }} \
-      #      --ossIndexUser ${{ secrets.OSSINDEX_USERNAME }} \
-      #      --ossIndexPassword ${{ secrets.OSSINDEX_PASSWORD }} || true
+      - name: Run OWASP Dependency-Check Scan
+        run: |
+          mkdir -p dependency-check-report
+          $HOME/dependency-check/dependency-check/bin/dependency-check.sh \
+            --project "java-springboot-app" \
+            --scan . \
+            --format HTML \
+            --out dependency-check-report \
+            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
+            --ossIndexUser ${{ secrets.OSSINDEX_USERNAME }} \
+            --ossIndexPassword ${{ secrets.OSSINDEX_PASSWORD }} || true
           
-      #- name: Upload Dependency Check Report
-      #  uses: actions/upload-artifact@v4
-      #  with:
-      #    name: dependency-check-report
-      #    path: dependency-check-report
+      - name: Upload Dependency Check Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: dependency-check-report
+          path: dependency-check-report
 
       # Build, Compile, and Test with Maven
       - name: Build & Test (Maven)
@@ -264,7 +264,7 @@ jobs:
           target: 'http://localhost:8090'
           cmd_options: '-m 3'                # Limit scan time to 3 minutes (optional)
           allow_issue_writing: false         # Don't create GitHub issues automatically
-          fail_action: false                  # if true then -> Fail pipeline on high/medium findings
+          fail_action: false                 # if true then -> Fail pipeline on high/medium findings
           artifact_name: 'zap-dast-report'   # Artifact ZIP will be auto-uploaded
           token: ${{ secrets.GITHUB_TOKEN }}
                 
